In [1]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [3]:
x = torch.randn((5,3))
x

tensor([[-0.0799,  0.3581, -1.2990],
        [-0.2101, -0.0296, -0.4725],
        [ 1.3037,  0.6319,  1.2907],
        [ 2.5902,  0.0919, -0.2769],
        [-0.4823, -1.4578, -0.7843]])

In [4]:
a = [1,3]
x[a]

tensor([[-0.2101, -0.0296, -0.4725],
        [ 2.5902,  0.0919, -0.2769]])

In [5]:
class A:
    pass

b = [A for i in range(5)]
b

[__main__.A, __main__.A, __main__.A, __main__.A, __main__.A]

In [7]:
y = x
z = x

In [17]:
prime_x = torch.cat([x,y,z], dim=-1)

In [13]:
for lol,i in enumerate(b):
    print(lol, i)

0 <class '__main__.A'>
1 <class '__main__.A'>
2 <class '__main__.A'>
3 <class '__main__.A'>
4 <class '__main__.A'>


In [20]:
F.softmax(prime_x).shape

C:\Users\bhara\AppData\Local\Temp\ipykernel_27980\3341546188.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(prime_x).shape


torch.Size([5, 9])

In [21]:
prime_x.shape

torch.Size([5, 9])

In [24]:
b[:0]

[]

In [35]:
x = {(1,2): 3, (3,4): 1}
new_x = max(x.items(), key = lambda item: item[1])
new_x

((1, 2), 3)

In [33]:
import regex as re    
def apply_regrex(text):
    gpt2pat = re.compile(r"""'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+""")
    tokens = re.findall(gpt2pat, text)
    tokens = [list(ch.encode('utf-8')) for ch in tokens]
    return tokens

x = apply_regrex("hello bharat how are you")
x

[[104, 101, 108, 108, 111],
 [32, 98, 104, 97, 114, 97, 116],
 [32, 104, 111, 119],
 [32, 97, 114, 101],
 [32, 121, 111, 117]]

In [37]:
count = {(1,2): 3, (3,4): 1, (2,3): 5, (1,6): 10}
merges = {(1,2): 3, (2,3): 10}
max_count = max(count.items(), key=lambda item: item[1] if item[0] in merges else float('-inf'))
max_count

((2, 3), 5)

In [38]:
len({"1": 1, "10": 10})

2

In [41]:
x = [10]
y = x*10
y

[10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

In [42]:
x = torch.randn((20,100))
y = torch.randn(100)

In [45]:
x = [1,2,3,4]
y = torch.tensor(x)
y

tensor([1, 2, 3, 4])

In [7]:
x = torch.randn((5,3))
y = x[:-1]
y.shape
x,y

(tensor([[-3.0350, -0.9484,  0.3995],
         [-0.4427, -1.1390,  1.3286],
         [ 0.6172, -1.2476, -0.0960],
         [ 0.2672, -0.3575,  0.2980],
         [ 0.1415, -0.3744,  0.7042]]),
 tensor([[-3.0350, -0.9484,  0.3995],
         [-0.4427, -1.1390,  1.3286],
         [ 0.6172, -1.2476, -0.0960],
         [ 0.2672, -0.3575,  0.2980]]))

In [8]:
new_x = [a[:-1] for a in x]
new_y = [a[1:] for a in y]
new_x, new_y

([tensor([-3.0350, -0.9484]),
  tensor([-0.4427, -1.1390]),
  tensor([ 0.6172, -1.2476]),
  tensor([ 0.2672, -0.3575]),
  tensor([ 0.1415, -0.3744])],
 [tensor([-0.9484,  0.3995]),
  tensor([-1.1390,  1.3286]),
  tensor([-1.2476, -0.0960]),
  tensor([-0.3575,  0.2980])])

In [15]:
a,b = zip(*list(zip(x,y)))
list(a),list(b)

([tensor([-3.0350, -0.9484,  0.3995]),
  tensor([-0.4427, -1.1390,  1.3286]),
  tensor([ 0.6172, -1.2476, -0.0960]),
  tensor([ 0.2672, -0.3575,  0.2980])],
 [tensor([-3.0350, -0.9484,  0.3995]),
  tensor([-0.4427, -1.1390,  1.3286]),
  tensor([ 0.6172, -1.2476, -0.0960]),
  tensor([ 0.2672, -0.3575,  0.2980])])

In [ ]:
tokens = torch.arange(1, 1001)
tokens.view(-1, 500)

In [10]:
tokens.shape

torch.Size([1000])